#!/bin/bash

# Copyright (c) 2026 Eliel de Paula <ulisse.falcucci@gmail.com>
# Licensed under the MIT License

show_help() {
    echo "Usage: gt <command> [options]"
    echo ""
    echo "Commands:"
    echo "  log                     Show commit history"
    echo "  update                  Check for new version"
    echo "  init                    Initialize git repository with '$PRD_BRANCH' and '$DEV_BRANCH'"
    echo "  feature new <name>      Create new feature branch (source: $PRD_FROM)"
    echo "  feature finish <name>   Merge feature into '$DEV_BRANCH'"
    echo "  feature send <name>     Push feature branch to remote"
    echo "  feature get <name>      Fetch and pull feature branch from remote"
    echo "  release new <name>      Create new release branch (source: $PRD_FROM)"
    echo "  release add <name>      Add feature to current release"
    echo "  release finish <name>   Finish release: merge into '$PRD_BRANCH', merge into '$DEV_BRANCH', and create tag"
    echo "  release send <name>     Push release branch to remote"
    echo "  release get <name>      Fetch and pull release branch from remote"
    echo "  hotfix new <name>       Create new hotfix branch (source: $PRD_BRANCH)"
    echo "  hotfix finish <name> <version>  Finish hotfix: merge into '$PRD_BRANCH', merge into '$DEV_BRANCH', and create tag"
    echo ""
    echo "Configuration (via git config):"
    echo "  gt.prd-branch=$PRD_BRANCH"
    echo "  gt.dev-branch=$DEV_BRANCH"
    echo "  gt.rel-branch=$REL_BRANCH"
    echo "  gt.fet-branch=$FET_BRANCH"
    echo "  gt.hot-branch=$HOT_BRANCH"
    echo "  gt.rel-prefix=$REL_PREFIX"
    echo "  gt.fet-prefix=$FET_PREFIX"
    echo "  gt.fet-from=$FET_FROM      (prd or dev)"
    echo "  gt.rel-from=$REL_FROM      (prd or dev)"
    echo "  gt.keep-feature=$KEEP_FEATURE    (y or n)"
    echo ""
    echo "To configure:"
    echo "  git config gt.prd-branch main"
    echo "  git config gt.dev-branch develop"
    echo "  git config gt.rel-branch release/"
    echo "  git config gt.fet-branch feature/"
    echo "  git config gt.hot-branch hotfix/"
    echo "  git config gt.rel-prefix \"\""
    echo "  git config gt.fet-prefix \"\""
    echo "  git config gt.fet-from dev   (or prd)"
    echo "  git config gt.rel-from dev   (or prd)"
    echo "  git config gt.keep-feature n (to remove feature branch after finish)"
}
